export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Trust } from "./Trust"
export { default as Industries } from "./Industries"
export { default as Choose } from "./Choose"
export {  Slider } from "./Slider"
export { default as Approach } from "./Approach"
export { default as Certificates } from "./Certificates"
export { default as InfiniteTestimonials } from "./InfiniteTestimonials"
export { default as Question } from "./Question"